language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get -y install task
script: |
  cargo build
  cargo test

  # prepare taskwarrior, initial setup
  yes | task

  for n in create_task; do
    cargo run --example "$n" | tee /tmp/"$n"
    task import /tmp/"$n" || exit 0

    # delete all tasks
    yes | task delete
  done

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | sed 's/-/_/'`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

notifications:
  irc:
    channels:
      - "chat.freenode.net#imag"
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"

env:
  global:
    secure: "VbHRzoQ8nYNB1acbCUqoHz0Vvki5SC71mzt04B3jPNIAFFEZ8+45769tEmOQ8vygzwIp2QaFzlG48CLGG/ne+NG1kS2sdGt0gakvGq0PMNBLUodtX9zGmc6GNGrFaJ9FlgYzUy8mRZSod93aHiH5W4IBfeJASUh1IOxSsoQ4qMvQG/g4yXto4RPazH+mBWUl0ClDuduC0n2Lt9/DPXCpbXn/wR/4fHIMG7yMg0DKFsvfJ8XgkwJG68BX3fJTsrnLuI8UG2ZmxYeNl2PhwlM5dfFXN6WmlRm8hhr0+t35YgpaP/DmM3qP2n5IVkYfn3L/R5dCVLLi/DVhhv2qTxNi6elQxBdawlFG0F/q4djKgg/iTtK0g2hjKYuP993JOfDDNMNKhkjaqSqror78zj+h4G+JNcajNINuj+cVCnNnU2UwwoHJ2rc+SynvMxra2M9frGpfgzU75rWf9v8yRcklEmVghkKHkIGPRaVITC/aasoe4UcYlQmoO4nQAMrzcDiP9YcE0qsJqtZ2XzaopnSMWnLVQCNuwgNAOkhDEt/TXj/JdQFvWqBs0oqePF63iDx/qrRpgHXwEqIFa2YPd8Kurhiv7NeqWpT06YbOO5FwJOvsrLZvfL9gtbUpoV9pXi8K3w/YmrR2YCBF0UWRoh85Z4eXkFm0+3yXZq5WVGkpt+U="
