[package]
name = "task-hookrs"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Crate to work with taskwarrior exported JSON"
keywords = [ "JSON", "json", "taskwarrior", "todo", "task", "binding", "import", "export"]

documentation = "https://matthiasbeyer.github.io/task-hookrs/task-hookrs/index.html"
homepage      = "https://github.com/matthiasbeyer/task-hookrs"
repository    = "https://github.com/matthiasbeyer/task-hookrs"
readme        = "./README.md"
license       = "LGPL-2.1"

[dependencies]
chrono = "0.2.20"
log = "0.3.5"
serde = "0.7.0"
serde_json = "0.7.0"
uuid = { version = "0.2.0", features = ["serde"] }

[dev-dependencies]
env_logger = "0.3.2"

